Importamos las librer√≠as:

In [1]:
#Importamos librerias

import camelot
import pandas as pd
import datetime
from funciones import tabla_a_datos, campos_calculados, separar_columna, juntar_columnas, separar_columna_derecha
import glob

Con *camelot* leemos el pdf que le digamos y extraemos las tablas en bruto:

In [3]:
## Datos a importar

file = 'NATACION_BENJAMIN_5_RESULTADOS_2122.pdf'
tablas = camelot.read_pdf(file, pages='all', flavor='stream', split_text='\n')
tablas.n

18

In [69]:
t0=tablas[0].df.copy()
t0.loc[10][1]=t0.loc[10][1]+'o'
t0.loc[10][2]='11'
t0=t0[t0[0]!=''][4:]

t1 = tablas[2].df[tablas[2].df[0]!=''][3:].drop(8,axis=1).T.reset_index(drop=True).T
t1 = juntar_columnas(juntar_columnas(separar_columna_derecha(separar_columna(t1,0),6),1,6),3,4)
t1[1]=t1[1].replace({'MENDEZSALVADOR, Carlos':'MENDEZ SALVADOR, Carlos',
                       'PETISMEROYO, Lucas':'PETISME ROYO, Lucas',
                     'PETISMEROYO,Lucas':'PETISME ROYO, Lucas',
                     'RAMOS OLMOS,Diego':'RAMOS OLMOS, Diego',
                      'SANCHEZMERCADO, Adrian':'SANCHEZ MERCADO, Adrian',
                      'MOSTEOHIDALGO, Carlos':'MOSTEO HIDALGO, Carlos',
                      'BERDEJOLOBERA, Guillermo':'BERDEJO LOBERA, Guillermo',
                     'GREGORIO FERNANDEZ,Enrique':'GREGORIO FERNANDEZ, Enrique',
                      'JIMENEZLAFUENTE, Daniel':'JIMENEZ LAFUENTE, Daniel',
                     'SANCHEZSAEZ, Alejandro':'SANCHEZ SAEZ, Alejandro',
                     'SANZ BEJENARIU,Diego':'SANZ BEJENARIU, Diego',
                     'VICENTEBARRA,Guillen':'VICENTE BARRA, Guillen',
                     'RAZABALINGELMO, Angel':'RAZABAL INGELMO, Angel',
                     'NEVADOPEREZ, Lorien':'NEVADO PEREZ, Lorien',
                     'RAMOSOLMOS,Diego':'RAMOS OLMOS, Diego',
                     'MARTINFERNANDEZ, Leo':'MARTIN FERNANDEZ, Leo',
                     'BARRIENDOS ZAMORA,Saul':'BARRIENDOS ZAMORA, Saul',
                     'RAMOSOLMOS,Marcos':'RAMOS OLMOS, Marcos',
                     'RUBIO RAKITIN,Larion Francisco':'RUBIO RAKITIN, Larion Francisco'
                     
                      })
t1[3]=t1[3].replace({'C.N.Helios':'C.N. Helios',
                       'P. SanAgustin':'P. San Agustin',
                     'E.M.El Olivar':'E.M. El Olivar'
                      })


t1b = tablas[3].df[3:]
t1b=t1b[t1b[0]!=''][:-2].drop(4,axis=1).T.reset_index(drop=True).T

t2 = tablas[4].df
t2=t2[t2[0]!=''][2:-1]
t2


# t2b=pd.read_csv('tabla_perdida_27_03_22.csv',dtype=str, header=None).T.reset_index(drop=True).T
# t2b.to_dict()
dic={0: {0: '9', 1: '10', 2: '11', 3: '12', 4: '13', 5: '14', 6: '15'},
 1: {0: 'MARTINEZ MARQUES, Aimar Teresa',
  1: 'GIMENO GOMEZ, Yaretzi Izel',
  2: 'REMACHA ROYO, Itziar',
  3: 'BORREGUERO PEDREIRA, Leire',
  4: 'GALAY TORRIJO, Celia',
  5: 'GARCIA ZABAL, Carmen',
  6: 'IZQUIERDO GRACIA, Maria'},
 2: {0: '13', 1: '13', 2: '13', 3: '13', 4: '13', 5: '13', 6: '13'},
 3: {0: 'Stadium Venecia',
  1: 'P. San Agustin',
  2: 'E.M. El Olivar',
  3: 'E.M. El Olivar',
  4: 'Stadium Venecia',
  5: 'P. San Agustin',
  6: 'Stadium Venecia'},
 4: {0: '1:57.36',
  1: '1:59.80',
  2: '2:07.92',
  3: '2:10.12',
  4: '2:13.72',
  5: '2:15.45',
  6: '2:45.36'},
 5: {0: '102', 1: '96', 2: '79', 3: '75', 4: '69', 5: '66', 6: '36'}}
t2b=pd.DataFrame(dic)

t2b

    0                               1   2                3        4    5
0   9  MARTINEZ MARQUES, Aimar Teresa  13  Stadium Venecia  1:57.36  102
1  10      GIMENO GOMEZ, Yaretzi Izel  13   P. San Agustin  1:59.80   96
2  11            REMACHA ROYO, Itziar  13   E.M. El Olivar  2:07.92   79
3  12      BORREGUERO PEDREIRA, Leire  13   E.M. El Olivar  2:10.12   75
4  13            GALAY TORRIJO, Celia  13  Stadium Venecia  2:13.72   69
5  14            GARCIA ZABAL, Carmen  13   P. San Agustin  2:15.45   66
6  15         IZQUIERDO GRACIA, Maria  13  Stadium Venecia  2:45.36   36

In [42]:
t4=tablas[8].df[3:]
t4

      0                              1   2                   3        4    5
3    1.               MARCO LOPEZ, Leo  11         C.N. Helios    37.82  190
4    2.     RODRIGUEZ ARTIEDA, Marcelo  11         C.N. Helios    38.25  183
5    3.          SERRABLO HUESO, Diego  11     Stadium Venecia    38.53  179
6    4.            LOPEZ VELEZ, Marcos  11      E.M. El Olivar    39.31  169
7    5.          CAVERO GARCIA, Daniel  11  Stadium Casablanca    42.12  137
8    6.            SANCHO GRAUS, Bruno  11      E.M. El Olivar    43.92  121
9    7.          ANGUAS FELIZ, Aquiles  11      E.M. El Olivar    45.03  112
10   8.        BESCOS RODRIGUEZ, Jesus  11      E.M. El Olivar    45.31  110
11   9.         POLO MARTINEZ, Nicolas  11         C.N. Helios    46.00  105
12  10.    MODREGO MARQUETA, Alejandro  11     Stadium Venecia    46.02  105
13  11.        FABRE GARCIA, Guillermo  11      E.M. El Olivar    47.76   94
14  12.          TATARU, Adrian Stefan  11      E.M. El Olivar    48.48   90
15  13.          BELTRAN VIEJO, Arturo  11      E.M. El Olivar    48.51   90
16  14.        MARTINEZ ANTUNEZ, Roman  11     Stadium Venecia    48.70   89
17  15.           FANDOS MARCO, Carlos  11      E.M. El Olivar    48.94   87
18  16.        LAFUENTE GARCIA, Victor  11         C.N. Helios    49.98   82
19  17.       ALCALDE MARTINEZ, Martin  11         C.N. Helios    52.31   71
20  18.  GARCIA DE LA SERNA, Alejandro  11         C.N. Helios    54.28   64
21  19.      NAVARRO PARDOS, Francisco  11          H2ogo C.N.    55.50   60
22  20.          ROMERO SANTOS, Kilian  11         C.N. Helios    55.70   59
23  21.         BORROY SANCHEZ, Martin  11  Stadium Casablanca    55.89   58
24  22.     BARCELONA PERALES, Beltran  11      E.M. El Olivar    59.86   47
25  23.     QUINTANILLA CARBAJO, Amaro  11          H2ogo C.N.  1:11.84   27

Modificamos las tablas

In [4]:
t0=separar_columna(tablas[0].df[tablas[0].df[0]!=''][4:],1)
t1 = tablas[1].df[tablas[1].df[0]!=''][3:].drop(8,axis=1).T.reset_index(drop=True).T
t1 = separar_columna(separar_columna(t1,0).fillna(value=''),0,' ').fillna(value='')
t1 = juntar_columnas(juntar_columnas(t1,1,6),3,4)
t1[1]=t1[1].replace({'MENDEZSALVADOR, Carlos':'MENDEZ SALVADOR, Carlos',
                       'PETISMEROYO, Lucas':'PETISME ROYO, Lucas',
                     'RAMOS OLMOS,Diego':'RAMOS OLMOS, Diego',
                      'SANCHEZMERCADO, Adrian':'SANCHEZ MERCADO, Adrian',
                      'MOSTEOHIDALGO, Carlos':'MOSTEO HIDALGO, Carlos',
                      'BERDEJOLOBERA, Guillermo':'BERDEJO LOBERA, Guillermo',
                     'GREGORIO FERNANDEZ,Enrique':'GREGORIO FERNANDEZ, Enrique',
                      'JIMENEZLAFUENTE, Daniel':'JIMENEZ LAFUENTE, Daniel',
                     'SANCHEZSAEZ, Alejandro':'SANCHEZ SAEZ, Alejandro',
                     'SANZ BEJENARIU,Diego':'SANZ BEJENARIU, Diego',
                     'VICENTEBARRA,Guillen':'VICENTE BARRA, Guillen',
                     'RAZABALINGELMO, Angel':'RAZABAL INGELMO, Angel',
                     'NEVADOPEREZ, Lorien':'NEVADO PEREZ, Lorien'                  
                      })
t1[3]=t1[3].replace({'C.N.Helios':'C.N. Helios',
                       'P. SanAgustin':'P. San Agustin',
                      })

# t1b=pd.read_csv('tabla_perdida_20_02_22.csv',dtype=str, header=None).T.reset_index(drop=True).T
# t1b.to_dict()
dic ={0: {0: '21.', 1: '22.', 2: '23.', 3: '24.'},
 1: {0: 'SANTAMARIA FERRERUELA, Carlos',
  1: 'SANCHEZ DUARTE, Rodrigo',
  2: 'CUEZVA JORDAN, Hector',
  3: 'PEREZ DOMINCHE, Oriol'},
 2: {0: '10', 1: '10', 2: '10', 3: '10'},
 3: {0: 'P. San Agustin',
  1: 'Stadium Venecia',
  2: 'Stadium Venecia',
  3: 'C.N. Helios'},
 4: {0: '3:27.36', 1: '3:34.13', 2: '3:34.20', 3: '3:53.64'},
 5: {0: '110', 1: '99', 2: '99', 3: '76'}}
t1b=pd.DataFrame(dic)

t2=tablas[2].df[tablas[2].df[0]!=''][2:]
# separar_columna(t2,2).fillna(value='').loc[17]
t2.loc[17][1]='MARTINEZ MARQUES, Aimar Teresa'
t2.loc[17][2]='13'

# t2b=pd.read_csv('tabla_perdida2_20_02_22.csv',dtype=str, header=None).T.reset_index(drop=True).T
# t2b.to_dict()
dic={0: {0: '10.',
  1: '11.',
  2: '12.',
  3: '13.',
  4: '14.',
  5: '15.',
  6: '16.',
  7: '17.'},
 1: {0: 'GIMENO GOMEZ, Yaretzi Izel',
  1: 'REMACHA ROYO, Itziar',
  2: 'RODRIGO MONFORTE, Lucia',
  3: 'SALUE√ëA LUCHA, Vera',
  4: 'BORREGUERO PEDREIRA, Leire',
  5: 'GALAY TORRIJO, Celia',
  6: 'MARIN PELEGRIN, Sara',
  7: 'MARIN PELEGRIN, Julia'},
 2: {0: '13', 1: '13', 2: '13', 3: '13', 4: '13', 5: '13', 6: '13', 7: '13'},
 3: {0: 'P. San Agustin',
  1: 'E.M. El Olivar',
  2: 'E.M. El Olivar',
  3: 'C.N. Helios',
  4: 'E.M. El Olivar',
  5: 'Stadium Venecia',
  6: 'H2ogo C.N.',
  7: 'H2ogo C.N.'},
 4: {0: '1:49.62',
  1: '1:53.45',
  2: '1:54.02',
  3: '1:57.72',
  4: '2:01.32',
  5: '2:03.50',
  6: '2:09.69',
  7: '2:09.74'},
 5: {0: '96', 1: '86', 2: '85', 3: '77', 4: '71', 5: '67', 6: '58', 7: '58'}}

t2b=pd.DataFrame(dic)

t2c=tablas[3].df[tablas[3].df[0]!=''][2:-2].drop(2,axis=1).T.reset_index(drop=True).T

t3=tablas[4].df[tablas[4].df[0]!=''][3:].drop(8,axis=1).T.reset_index(drop=True).T
t3 = separar_columna(separar_columna(t3,0).fillna(value=''),0,' ').fillna(value='')
t3 = juntar_columnas(juntar_columnas(t3,1,5),3,4)
t3[1]=t3[1].replace({'CASTILLOPRADO, Neus':'CASTILLO PRADO, Neus',
                       'LAMBANGAVE, Ines':'LAMBAN GAVE, Ines',
                     'SIMON HEREDIA,Ariadna':'SIMON HEREDIA, Ariadna',
                      'RAZABALINGELMO, Naiara':'RAZABAL INGELMO, Naiara',
                      'GIMENOMONREAL, Manuela':'GIMENO MONREAL, Manuela',
                      'PERALESCASAS, Laura':'PERALES CASAS, Laura',
                     'BARRACHINA ARTAZCOZ,Nahia':'BARRACHINA ARTAZCOZ, Nahia',
                      'ALONSOMORA,Naiara':'ALONSO MORA, Naiara',
                     'RAZABALINGELMO, Anahi':'RAZABAL INGELMO, Anahi',
                     'ORTEGAFRAGOSO, Emma':'ORTEGA FRAGOSO, Emma',
                     'RASAL ALVAREZ,Maria':'RASAL ALVAREZ, Maria',
                     'CEBRIANPUEYO, Carolina':'CEBRIAN PUEYO, Carolina',
                     'ROMEROLORENTE, Paula':'ROMERO LORENTE, Paula'                  
                      })
t3[3]=t3[3].replace({'C.N.Helios':'C.N. Helios',
                       'P. SanAgustin':'P. San Agustin',
                      })
t3b=tablas[5].df[tablas[5].df[0]!=''][3:].drop(8,axis=1).T.reset_index(drop=True).T
t3b = separar_columna(separar_columna(t3b,0).fillna(value=''),0,' ').fillna(value='')
t3b = juntar_columnas(juntar_columnas(t3b,1,6),3,4)
t3b[1]=t3b[1].replace({'CASTILLOPRADO, Neus':'CASTILLO PRADO, Neus',
                       'LAMBANGAVE, Ines':'LAMBAN GAVE, Ines',
                     'SIMON HEREDIA,Ariadna':'SIMON HEREDIA, Ariadna',
                      'RAZABALINGELMO, Naiara':'RAZABAL INGELMO, Naiara',
                      'GIMENOMONREAL, Manuela':'GIMENO MONREAL, Manuela',
                      'PERALESCASAS, Laura':'PERALES CASAS, Laura',
                     'BARRACHINA ARTAZCOZ,Nahia':'BARRACHINA ARTAZCOZ, Nahia',
                      'ALONSOMORA,Naiara':'ALONSO MORA, Naiara',
                     'RAZABALINGELMO, Anahi':'RAZABAL INGELMO, Anahi',
                     'ORTEGAFRAGOSO, Emma':'ORTEGA FRAGOSO, Emma',
                     'RASAL ALVAREZ,Maria':'RASAL ALVAREZ, Maria',
                     'CEBRIANPUEYO, Carolina':'CEBRIAN PUEYO, Carolina',
                     'ROMEROLORENTE, Paula':'ROMERO LORENTE, Paula'                  
                      })
t3b[3]=t3b[3].replace({'C.N.Helios':'C.N. Helios',
                       'P. SanAgustin':'P. San Agustin',
                      })

t4=separar_columna(tablas[6].df[tablas[6].df[0]!=''][2:],1)
t4.loc[19][1]='MODREGO MARQUETA, Alejandro'
t4.loc[19][2]='11'

# t4b=pd.read_csv('tabla_perdida3_20_02_22.csv',dtype=str, header=None).T.reset_index(drop=True).T
# t4b.to_dict()
dic={0: {0: '10.', 1: '11.'},
 1: {0: 'LOPEZ VELEZ, Marcos', 1: 'BEAMONTE MARTIN, Diego'},
 2: {0: '11', 1: '11'},
 3: {0: 'E.M. El Olivar', 1: 'P. San Agustin'},
 4: {0: '1:48.31', 1: '1:52.44'},
 5: {0: '133', 1: '119'}}
t4b=pd.DataFrame(dic)


t4c=tablas[7].df[tablas[7].df[0]!=''][2:-4]
t4c=separar_columna(t4c,1)

t5=tablas[8].df[tablas[8].df[0]!=''][2:]
t5=juntar_columnas(juntar_columnas(separar_columna(t5,0).fillna(value=''),1,5),3,4).drop(4,axis=1).T.reset_index(drop=True).T
t5[1]=t5[1].replace({'MENDEZSALVADOR, Carlos':'MENDEZ SALVADOR, Carlos',
                       'PETISMEROYO, Lucas':'PETISME ROYO, Lucas',
                     'RAMOS OLMOS,Diego':'RAMOS OLMOS, Diego',
                      'SANCHEZMERCADO, Adrian':'SANCHEZ MERCADO, Adrian',
                      'MOSTEOHIDALGO, Carlos':'MOSTEO HIDALGO, Carlos',
                      'BERDEJOLOBERA, Guillermo':'BERDEJO LOBERA, Guillermo',
                     'GREGORIO FERNANDEZ,Enrique':'GREGORIO FERNANDEZ, Enrique',
                      'JIMENEZLAFUENTE, Daniel':'JIMENEZ LAFUENTE, Daniel',
                     'SANCHEZSAEZ, Alejandro':'SANCHEZ SAEZ, Alejandro',
                     'SANZ BEJENARIU,Diego':'SANZ BEJENARIU, Diego',
                     'VICENTEBARRA,Guillen':'VICENTE BARRA, Guillen',
                     'RAZABALINGELMO, Angel':'RAZABAL INGELMO, Angel',
                     'NEVADOPEREZ, Lorien':'NEVADO PEREZ, Lorien',
                     'RAMOS OLMOS,Marcos':'RAMOS OLMOS, Marcos',
                      })
t5[3]=t5[3].replace({'C.N.Helios':'C.N. Helios',
                       'P. SanAgustin':'P. San Agustin',
                      })

t5b=tablas[9].df[tablas[9].df[0]!=''][2:]
t5b=juntar_columnas(juntar_columnas(separar_columna(separar_columna(t5b,0),0,' ').fillna(value=''),1,6),3,4).drop(4,axis=1).T.reset_index(drop=True).T
t5b[1]=t5b[1].replace({'MENDEZSALVADOR, Carlos':'MENDEZ SALVADOR, Carlos',
                       'PETISMEROYO, Lucas':'PETISME ROYO, Lucas',
                     'RAMOS OLMOS,Diego':'RAMOS OLMOS, Diego',
                      'SANCHEZMERCADO, Adrian':'SANCHEZ MERCADO, Adrian',
                      'MOSTEOHIDALGO, Carlos':'MOSTEO HIDALGO, Carlos',
                      'BERDEJOLOBERA, Guillermo':'BERDEJO LOBERA, Guillermo',
                     'GREGORIO FERNANDEZ,Enrique':'GREGORIO FERNANDEZ, Enrique',
                      'JIMENEZLAFUENTE, Daniel':'JIMENEZ LAFUENTE, Daniel',
                     'SANCHEZSAEZ, Alejandro':'SANCHEZ SAEZ, Alejandro',
                     'SANZ BEJENARIU,Diego':'SANZ BEJENARIU, Diego',
                     'VICENTEBARRA,Guillen':'VICENTE BARRA, Guillen',
                     'RAZABALINGELMO, Angel':'RAZABAL INGELMO, Angel',
                     'NEVADOPEREZ, Lorien':'NEVADO PEREZ, Lorien',
                     'RAMOS OLMOS,Marcos':'RAMOS OLMOS, Marcos',
                       'SANCHEZ SAEZ,Alejandro':'SANCHEZ SAEZ, Alejandro',
                       'DANIELROYO, Carlos':'DANIEL ROYO, Carlos',
                       'MARTINFERNANDEZ, Leo':'MARTIN FERNANDEZ, Leo',
                       'CUEZVAJORDAN, Hector':'CUEZVA JORDAN, Hector',
                       'ESTAUNLOPEZ,Marcos':'ESTAUN LOPEZ, Marcos',
                       'NEVADOPEREZ,Lorien':'NEVADO PEREZ, Lorien',
                       
                       
                      })
t5b[3]=t5b[3].replace({'C.N.Helios':'C.N. Helios',
                       'P. SanAgustin':'P. San Agustin',
                      })
# t6=pd.read_csv('tabla_perdida4_20_02_22.csv',dtype=str, header=None).T.reset_index(drop=True).T
# dic=t6.to_dict()

dic={0: {0: '1.', 1: '2.', 2: '3.', 3: '4.', 4: '5.'},
 1: {0: 'ESCORIHUELA AZNAR, Claudia',
  1: 'RODRIGUEZ SOLANAS, Ines',
  2: 'MALON CANTIN, Sofia',
  3: 'MALO SANCHEZ, Paula',
  4: 'REMACHA ROYO, Itziar'},
 2: {0: '13', 1: '13', 2: '13', 3: '13', 4: '13'},
 3: {0: 'E.M. El Olivar',
  1: 'E.M. El Olivar',
  2: 'C.N. Helios',
  3: 'C.N. Helios',
  4: 'E.M. El Olivar'},
 4: {0: '1:59.04', 1: '2:02.81', 2: '2:07.84', 3: '2:09.72', 4: '2:09.95'},
 5: {0: '143', 1: '130', 2: '116', 3: '111', 4: '110'}}
t6=pd.DataFrame(dic)


t6b=tablas[10].df[tablas[10].df[0]!=''][2:-4]

t6b.loc[13][1]='MARTINEZ MARQUES, Aimar Teresa'
t6b.loc[13][2]='13'

# t7=pd.read_csv('tabla_perdida5_20_02_22.csv',dtype=str, header=None).T.reset_index(drop=True).T
# dic=t7.to_dict()

dic={0: {0: '1.', 1: '2.', 2: '3.', 3: '4.', 4: '5.'},
 1: {0: 'CASTILLO PRADO, Neus',
  1: 'IOVU, Mireya',
  2: 'GIL FUENTES, Izarbe',
  3: 'BERGES ALAEZ, Africa',
  4: 'GIMENO MONREAL, Manuela'},
 2: {0: '12', 1: '12', 2: '12', 3: '12', 4: '12'},
 3: {0: 'E.M. El Olivar',
  1: 'P. San Agustin',
  2: 'Stadium Venecia',
  3: 'E.M. El Olivar',
  4: 'E.M. El Olivar'},
 4: {0: '3:36.21', 1: '3:53.82', 2: '3:56.09', 3: '3:57.59', 4: '3:58.62'},
 5: {0: '241', 1: '190', 2: '185', 3: '181', 4: '179'}}

t7=pd.DataFrame(dic)

t7b = tablas[11].df[tablas[11].df[0]!=''][2:-1].drop(8,axis=1).T.reset_index(drop=True).T
t7b = separar_columna(separar_columna(t7b,0).fillna(value=''),0,' ').fillna(value='')
t7b = juntar_columnas(juntar_columnas(t7b,1,6),3,4)
t7b[1]=t7b[1].replace({'CASTILLOPRADO, Neus':'CASTILLO PRADO, Neus',
                       'LAMBANGAVE, Ines':'LAMBAN GAVE, Ines',
                     'SIMON HEREDIA,Ariadna':'SIMON HEREDIA, Ariadna',
                      'RAZABALINGELMO, Naiara':'RAZABAL INGELMO, Naiara',
                      'GIMENOMONREAL, Manuela':'GIMENO MONREAL, Manuela',
                      'PERALESCASAS, Laura':'PERALES CASAS, Laura',
                     'BARRACHINA ARTAZCOZ,Nahia':'BARRACHINA ARTAZCOZ, Nahia',
                      'ALONSOMORA,Naiara':'ALONSO MORA, Naiara',
                     'RAZABALINGELMO, Anahi':'RAZABAL INGELMO, Anahi',
                     'ORTEGAFRAGOSO, Emma':'ORTEGA FRAGOSO, Emma',
                     'RASAL ALVAREZ,Maria':'RASAL ALVAREZ, Maria',
                     'CEBRIANPUEYO, Carolina':'CEBRIAN PUEYO, Carolina',
                     'ROMEROLORENTE, Paula':'ROMERO LORENTE, Paula',
                     'SIMONHEREDIA, Ariadna':'SIMON HEREDIA, Ariadna',
                     
                      })
t7b[3]=t7b[3].replace({'C.N.Helios':'C.N. Helios',
                       'P. SanAgustin':'P. San Agustin',
                      })

In [70]:
# Liga Benjamin

competicion = 'Benjam√≠n, jornada 5'
lugar = 'P. San Agustin'
fecha = datetime.datetime(2022,3,27)


lista_df=[
tabla_a_datos(t0, fila_datos = 0, fecha=fecha, prueba='100m Espalda', m_f='M', tipo=1, competicion=competicion, lugar= lugar),
tabla_a_datos(t1, fila_datos = 0, fecha=fecha, prueba='200m Espalda', m_f='M', tipo=1, competicion=competicion, lugar= lugar),
tabla_a_datos(t1b, fila_datos = 0, fecha=fecha, prueba='200m Espalda', m_f='M', tipo=1, competicion=competicion, lugar= lugar),
tabla_a_datos(t2, fila_datos = 0, fecha=fecha, prueba='100m Libre', m_f='F', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t2b, fila_datos = 0, fecha=fecha, prueba='100m Libre', m_f='F', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t2c, fila_datos = 0, fecha=fecha, prueba='100m Libre', m_f='F', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t3, fila_datos = 0, fecha=fecha, prueba='200m Libre', m_f='F', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t3b, fila_datos = 0, fecha=fecha, prueba='200m Libre', m_f='F', tipo=1, competicion=competicion, lugar= lugar),
tabla_a_datos(t4, fila_datos = 0, fecha=fecha, prueba='50m Mariposa', m_f='M', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t4b, fila_datos = 0, fecha=fecha, prueba='100m Braza', m_f='M', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t4c, fila_datos = 0, fecha=fecha, prueba='100m Braza', m_f='M', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t5, fila_datos = 0, fecha=fecha, prueba='200m Braza', m_f='M', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t5b, fila_datos = 0, fecha=fecha, prueba='200m Braza', m_f='M', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t6, fila_datos = 0, fecha=fecha, prueba='100m Braza', m_f='F', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t6b, fila_datos = 0, fecha=fecha, prueba='100m Braza', m_f='F', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t7, fila_datos = 0, fecha=fecha, prueba='200m Braza', m_f='F', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t7b, fila_datos = 0, fecha=fecha, prueba='200m Braza', m_f='F', tipo=1, competicion=competicion, lugar= lugar),

 ]

for d in lista_df :
    display(d)
    
    
campos_calculados(pd.concat(lista_df)).to_csv('competicion_'+competicion+'.csv', index=False)

,Puesto,Nombre,Anyo_nac,Club,Tiempo,Pts,Fecha,Prueba,Piscina,M_F,Competicion,Lugar
0,1.,"MARCO LOPEZ, Leo",11,C.N. Helios,1:24.38,187,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
1,2.,"LOPEZ VELEZ, Marcos",11,E.M. El Olivar,1:27.66,167,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
2,3.,"CAVERO GARCIA, Daniel",11,Stadium Casablanca,1:28.42,163,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
3,4.,"MODREGO MARQUETA, Alejandro",11,Stadium Venecia,1:28.70,161,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
4,5.,"SERRABLO HUESO, Diego",11,Stadium Venecia,1:29.12,159,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
5,6.,"BESCOS RODRIGUEZ, Jesus",11,E.M. El Olivar,1:31.00,149,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
6,7.,"TATARU, Adrian Stefan",11,E.M. El Olivar,1:31.51,147,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
7,8.,"ANGUAS FELIZ, Aquiles",11,E.M. El Olivar,1:32.75,141,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
8,9.,"RODRIGUEZ ARTIEDA, Marcelo",11,C.N. Helios,1:33.59,137,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
9,10.,"BELTRAN VIEJO, Arturo",11,E.M. El Olivar,1:35.11,131,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
10,11.,"SANCHO GRAUS, Bruno",11,E.M. El Olivar,1:37.34,122,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
11,12.,"LAFUENTE GARCIA, Victor",11,C.N. Helios,1:39.42,114,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
12,13.,"POLO MARTINEZ, Nicolas",11,C.N. Helios,1:40.26,112,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
13,14.,"ROMERO SANTOS, Kilian",11,C.N. Helios,1:42.06,106,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
14,15.,"BORROY SANCHEZ, Martin",11,Stadium Casablanca,1:42.47,104,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
15,16.,"MARTINEZ ANTUNEZ, Roman",11,Stadium Venecia,1:43.15,102,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
16,17.,"FANDOS MARCO, Carlos",11,E.M. El Olivar,1:43.20,102,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
17,18.,"NAVARRO PARDOS, Francisco",11,H2ogo C.N.,1:45.10,97,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
18,19.,"FABRE GARCIA, Guillermo",11,E.M. El Olivar,1:46.10,94,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
19,20.,"ALCALDE MARTINEZ, Martin",11,C.N. Helios,1:47.57,90,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
20,21.,"GARCIA DE LA SERNA, Alejandro",11,C.N. Helios,1:50.74,83,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
21,22.,"BARCELONA PERALES, Beltran",11,E.M. El Olivar,1:58.54,67,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
22,23.,"QUINTANILLA CARBAJO, Amaro",11,H2ogo C.N.,2:09.20,52,2022-03-27,100m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin

,Puesto,Nombre,Anyo_nac,Club,Tiempo,Pts,Fecha,Prueba,Piscina,M_F,Competicion,Lugar
0,1.,"RAMOS OLMOS, Diego",10,P. San Agustin,2:52.11,231,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
1,2.,"MENDEZ SALVADOR, Carlos",10,C.N. Teruel,2:52.82,228,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
2,3.,"MARTIN FERNANDEZ, Leo",10,E.M. El Olivar,2:59.11,205,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
3,4.,"PETISME ROYO, Lucas",10,E.M. El Olivar,3:03.06,192,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
4,5.,"BARRIENDOS ZAMORA, Saul",10,C.N. Helios,3:03.38,191,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
5,6.,"RAMOS OLMOS, Marcos",10,P. San Agustin,3:07.48,178,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
6,7.,"SANCHEZ MERCADO, Adrian",10,Stadium Casablanca,3:08.44,176,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
7,8.,"GREGORIO FERNANDEZ, Enrique",10,P. San Agustin,3:09.64,172,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
8,9.,"MOSTEO HIDALGO, Carlos",10,E.M. El Olivar,3:10.66,170,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
9,10.,"BERDEJO LOBERA, Guillermo",10,E.M. El Olivar,3:12.82,164,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
10,11.,"REVUELTO TELLO, Alejandro",10,E.M. El Olivar,3:16.50,155,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
11,12.,"SANZ BEJENARIU, Diego",10,C.N. Iz Cuarte,3:23.36,140,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
12,13.,"RUBIO RAKITIN, Larion Francisco",10,C.N. Helios,3:25.80,135,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
13,14.,"VARGASCIRUELOS, Carlos Nicolas",10,E.M. El Olivar,3:26.48,133,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
14,15.,"SANTAMARIA FERRERUELA, Carlos",10,P. San Agustin,3:27.02,132,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
15,16.,"VICENTEBARRA, Guillen",10,H2ogoC.N.,3:28.72,129,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
16,17.,"JIMENEZ LAFUENTE, Daniel",10,C.N. Helios,3:29.15,128,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
17,18.,"RAZABAL INGELMO, Angel",10,E.M. El Olivar,3:31.06,125,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
18,19.,"AGON LOPEZ, Javier",10,Stadium Casablanca,3:40.31,110,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin

,Puesto,Nombre,Anyo_nac,Club,Tiempo,Pts,Fecha,Prueba,Piscina,M_F,Competicion,Lugar
0,20.,"TELLO GRACIA, Aaron",10,C.N. Helios,3:44.31,104,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
1,21.,"NEVADO PEREZ, Lorien",10,C.N. Helios,3:45.95,102,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
2,22.,"CUEZVA JORDAN, Hector",10,Stadium Venecia,3:51.23,95,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
3,23.,"SANCHEZ DUARTE, Rodrigo",10,Stadium Venecia,4:09.02,76,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
4,24.,"PEREZ DOMINCHE, Oriol",10,C.N. Helios,4:16.06,70,2022-03-27,200m Espalda,25m,M,"Benjam√≠n, jornada 5",P. San Agustin

,Puesto,Nombre,Anyo_nac,Club,Tiempo,Pts,Fecha,Prueba,Piscina,M_F,Competicion,Lugar
0,1.,"RODRIGUEZ SOLANAS, Ines",13,E.M. El Olivar,1:44.10,146,2022-03-27,100m Libre,25m,F,"Benjam√≠n, jornada 5",P. San Agustin
1,2.,"GAINSINSKY CASTILLO, Michelle",13,C.N. Helios,1:45.89,139,2022-03-27,100m Libre,25m,F,"Benjam√≠n, jornada 5",P. San Agustin
2,3.,"MALON CANTIN, Sofia",13,C.N. Helios,1:48.00,131,2022-03-27,100m Libre,25m,F,"Benjam√≠n, jornada 5",P. San Agustin
3,4.,"MALO SANCHEZ, Paula",13,C.N. Helios,1:49.69,125,2022-03-27,100m Libre,25m,F,"Benjam√≠n, jornada 5",P. San Agustin
4,5.,"ESCORIHUELA AZNAR, Claudia",13,E.M. El Olivar,1:49.92,124,2022-03-27,100m Libre,25m,F,"Benjam√≠n, jornada 5",P. San Agustin
5,6.,"RODRIGO LORENTE, Claudia",13,Stadium Venecia,1:52.42,116,2022-03-27,100m Libre,25m,F,"Benjam√≠n, jornada 5",P. San Agustin
6,7.,"DEL BARRIO MIGUEL, Vera",13,Stadium Venecia,1:53.55,112,2022-03-27,100m Libre,25m,F,"Benjam√≠n, jornada 5",P. San Agustin
7,8.,"MARTIN SORIA, Claudia",13,Stadium Venecia,1:53.89,111,2022-03-27,100m Libre,25m,F,"Benjam√≠n, jornada 5",P. San Agustin

,Puesto,Nombre,Anyo_nac,Club,Tiempo,Pts,Fecha,Prueba,Piscina,M_F,Competicion,Lugar
0,1.,"MARCO LOPEZ, Leo",11,C.N. Helios,37.82,190,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
1,2.,"RODRIGUEZ ARTIEDA, Marcelo",11,C.N. Helios,38.25,183,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
2,3.,"SERRABLO HUESO, Diego",11,Stadium Venecia,38.53,179,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
3,4.,"LOPEZ VELEZ, Marcos",11,E.M. El Olivar,39.31,169,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
4,5.,"CAVERO GARCIA, Daniel",11,Stadium Casablanca,42.12,137,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
5,6.,"SANCHO GRAUS, Bruno",11,E.M. El Olivar,43.92,121,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
6,7.,"ANGUAS FELIZ, Aquiles",11,E.M. El Olivar,45.03,112,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
7,8.,"BESCOS RODRIGUEZ, Jesus",11,E.M. El Olivar,45.31,110,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
8,9.,"POLO MARTINEZ, Nicolas",11,C.N. Helios,46.00,105,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
9,10.,"MODREGO MARQUETA, Alejandro",11,Stadium Venecia,46.02,105,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
10,11.,"FABRE GARCIA, Guillermo",11,E.M. El Olivar,47.76,94,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
11,12.,"TATARU, Adrian Stefan",11,E.M. El Olivar,48.48,90,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
12,13.,"BELTRAN VIEJO, Arturo",11,E.M. El Olivar,48.51,90,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
13,14.,"MARTINEZ ANTUNEZ, Roman",11,Stadium Venecia,48.70,89,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
14,15.,"FANDOS MARCO, Carlos",11,E.M. El Olivar,48.94,87,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
15,16.,"LAFUENTE GARCIA, Victor",11,C.N. Helios,49.98,82,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
16,17.,"ALCALDE MARTINEZ, Martin",11,C.N. Helios,52.31,71,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
17,18.,"GARCIA DE LA SERNA, Alejandro",11,C.N. Helios,54.28,64,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
18,19.,"NAVARRO PARDOS, Francisco",11,H2ogo C.N.,55.50,60,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
19,20.,"ROMERO SANTOS, Kilian",11,C.N. Helios,55.70,59,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
20,21.,"BORROY SANCHEZ, Martin",11,Stadium Casablanca,55.89,58,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
21,22.,"BARCELONA PERALES, Beltran",11,E.M. El Olivar,59.86,47,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin
22,23.,"QUINTANILLA CARBAJO, Amaro",11,H2ogo C.N.,1:11.84,27,2022-03-27,50m Mariposa,25m,M,"Benjam√≠n, jornada 5",P. San Agustin

Hacemos un resumen de los datos contando el n√∫mero de nadadores por club:

In [71]:
# Resumen de datos

df=pd.read_csv('competicion_'+competicion+'.csv')

#df.pivot_table(df, values = 'Nombre',index='M_F', columns=['Club','Anyo_nac'], aggfunc=lambda x: len(x.unique()))
df.pivot_table(values = 'Nombre', columns='M_F', index=['Club','Anyo_nac'], aggfunc=lambda x: len(x.unique())).unstack().fillna(0).astype(int)

M_F                 F        M
Anyo_nac           10 11 13 10 11 13
Club
C.N. Helios         0  0  3  6  7  0
C.N. Iz Cuarte      0  0  0  1  0  0
C.N. Teruel         0  0  0  1  0  0
E.M. El Olivar      0  0  2  7  9  0
H2ogo C.N.          0  0  0  0  2  0
H2ogoC.N.           0  0  0  1  0  0
P. San Agustin      0  0  0  4  0  0
Stadium Casablanca  0  0  0  2  2  0
Stadium Venecia     0  0  3  2  3  0

Por √∫ltimo, a√±adimos todas las competiciones al archivo *base_datos.csv*:

In [72]:
# Actualizamos la base de datos

import glob

# Buscamos todos los ficheros csv correspondientes a competiciones los concatenamos y los grabamos en base de datos

lista_competiciones = glob.glob('competicion*.csv')
# lista_competiciones.reverse()
lista_competiciones.sort()
df=pd.concat([pd.read_csv(comp) for comp in lista_competiciones])
# df.sort_values(by='Fecha').to_csv('base_datos.csv', index=False)
df.to_csv('base_datos.csv', index=False)

# lista_competiciones.reverse()
lista_competiciones

['competicion_Benjam√≠n, jornada 1.csv',
 'competicion_Benjam√≠n, jornada 2.csv',
 'competicion_Benjam√≠n, jornada 3.csv',
 'competicion_Benjam√≠n, jornada 4.csv',
 'competicion_Benjam√≠n, jornada 5.csv']