Importamos las librer√≠as:

In [1]:
#Importamos librerias

import camelot
import pandas as pd
import datetime
from funciones import tabla_a_datos, campos_calculados, separar_columna, juntar_columnas, separar_columna_derecha
import glob

Con *camelot* leemos el pdf que le digamos y extraemos las tablas en bruto:

In [2]:
## Datos a importar

file = 'NATACION_BENJAMIN_6_RESULTADOS_2122.pdf'
tablas = camelot.read_pdf(file, pages='all', flavor='stream', split_text='\n')
tablas.n

11

In [84]:
dic_clubes={'C.N.Helios':'C.N. Helios','P. SanAgustin':'P. San Agustin','E.M.El Olivar':'E.M. El Olivar',
           'H2ogoC.N.':'H2ogo C.N.'}
dic_nadadores={'MARCOLOPEZ,Leo':'MARCO LOPEZ, Leo','MODREGO MARQUETA,Alejandro':'MODREGO MARQUETA, Alejandro',
              'CAVEROGARCIA, Daniel':'CAVERO GARCIA, Daniel','BESCOSRODRIGUEZ, Jesus':'BESCOS RODRIGUEZ, Jesus',
               'FABRE GARCIA,Guillermo':'FABRE GARCIA, Guillermo','SANCHOGRAUS, Bruno':'SANCHO GRAUS, Bruno',
               'FANDOSMARCO, Carlos':'FANDOS MARCO, Carlos','ANGUASFELIZ,Aquiles':'ANGUAS FELIZ, Aquiles',
               'ROMEROSANTOS, Kilian':'ROMERO SANTOS, Kilian','GARCIADE LA SERNA, Alejandro':'GARCIA DE LA SERNA, Alejandro',
               'PELEGRIN RUIZ,Raul':'PELEGRIN RUIZ, Raul','BARCELONA PERALES,Beltran':'BARCELONA PERALES, Beltran'
              }
t0=tablas[0].df[4:-6]
t0=t0[t0[0]!='']
t0=juntar_columnas(juntar_columnas(separar_columna_derecha(separar_columna(t0,0),6),1,6),3,4).replace(dic_clubes).replace(dic_nadadores).drop(4,axis=1).T.reset_index(drop=True).T


t1=tablas[2].df[4:]
t1=t1[t1[0]!=''].drop(4,axis=1).T.reset_index(drop=True).T


t1b=tablas[4].df[tablas[4].df[0]!=''][2:-6].drop(4,axis=1).T.reset_index(drop=True).T


# t2=pd.read_csv('tabla_perdida1_24_04_22.csv',dtype=str, header=None).T.reset_index(drop=True).T
# t2.to_dict()

dic={0: {0: '1.',
  1: '2.',
  2: '3.',
  3: '4.',
  4: '5.',
  5: '6.',
  6: '7.',
  7: '8.',
  8: '9.',
  9: '10.',
  10: '11.',
  11: '12.',
  12: '13.',
  13: '14.',
  14: '15.',
  15: '16.',
  16: '17.',
  17: '18.',
  18: '19.'},
 1: {0: 'RODRIGUEZ SOLANAS, Ines',
  1: 'MARTIN SORIA, Claudia',
  2: 'MALON CANTIN, Sofia',
  3: 'MALO SANCHEZ, Paula',
  4: 'ESCORIHUELA AZNAR, Claudia',
  5: 'GAINSINSKY CASTILLO, Michelle',
  6: 'DEL BARRIO MIGUEL, Vera',
  7: 'RODRIGO MONFORTE, Lucia',
  8: 'LEAL PELEGRIN, Julieta',
  9: 'GIMENO GOMEZ, Yaretzi Izel',
  10: 'RODRIGO LORENTE, Claudia',
  11: 'ZAPATA FERNANDEZ, Jara',
  12: 'REMACHA ROYO, Itziar',
  13: 'MARTINEZ MARQUES, Aimar Teresa',
  14: 'BORREGUERO PEDREIRA, Leire',
  15: 'GARCIA RODRIGUEZ, Aroa',
  16: 'ROLDAN POZO, Adriana',
  17: 'GARCIA ZABAL, Carmen',
  18: 'MATA AGUELA, Candela'},
 2: {0: '13',
  1: '13',
  2: '13',
  3: '13',
  4: '13',
  5: '13',
  6: '13',
  7: '13',
  8: '13',
  9: '13',
  10: '13',
  11: '13',
  12: '13',
  13: '13',
  14: '13',
  15: '13',
  16: '13',
  17: '13',
  18: '13'},
 3: {0: 'E.M. El Olivar',
  1: 'Stadium Venecia',
  2: 'C.N. Helios',
  3: 'C.N. Helios',
  4: 'E.M. El Olivar',
  5: 'C.N. Helios',
  6: 'Stadium Venecia',
  7: 'E.M. El Olivar',
  8: 'E.M. El Olivar',
  9: 'P. San Agustin',
  10: 'Stadium Venecia',
  11: 'Stadium Venecia',
  12: 'E.M. El Olivar',
  13: 'Stadium Venecia',
  14: 'E.M. El Olivar',
  15: 'C.N. Helios',
  16: 'P. San Agustin',
  17: 'P. San Agustin',
  18: 'E.M. El Olivar'},
 4: {0: '3:39.29',
  1: '3:41.78',
  2: '3:42.75',
  3: '3:45.48',
  4: '3:50.59',
  5: '3:53.56',
  6: '3:59.60',
  7: '4:04.36',
  8: '4:05.81',
  9: '4:11.51',
  10: '4:14.41',
  11: '4:17.18',
  12: '4:17.73',
  13: '4:27.62',
  14: '4:42.56',
  15: '4:57.91',
  16: '5:11.00',
  17: '5:21.41',
  18: '5:21.54'},
 5: {0: '171',
  1: '165',
  2: '163',
  3: '157',
  4: '147',
  5: '142',
  6: '131',
  7: '124',
  8: '121',
  9: '113',
  10: '109',
  11: '106',
  12: '105',
  13: '94',
  14: '80',
  15: '68',
  16: '60',
  17: '54',
  18: '54'}}

t2=pd.DataFrame(dic)

t3=tablas[7].df[3:]
t3=t3[t3[0]!=''].drop(4,axis=1).T.reset_index(drop=True).T

t3b=tablas[8].df[3:]
# t3=t3[t3[0]!=''].drop(4,axis=1).T.reset_index(drop=True).T
t3b[t3b[0]!=''][:-2].drop(4,axis=1).T.reset_index(drop=True).T

      0                             1   2                   3 4        5    6
3   19.         BERGES ALAEZ, Daniela  12      E.M. El Olivar    4:10.02  115
5   20.              PES URREA, Pilar  12      P. San Agustin    4:20.62  102
7   21.       CEBRIAN PUEYO, Carolina  12      P. San Agustin    4:25.20   97
9   22.  GALIPIENZO NAVARRO, Cristina  12     Stadium Venecia    4:26.57   95
11  23.     GALIPIENZO NAVARRO, Paula  12     Stadium Venecia    4:31.19   90
13  24.          SANCHEZ AGUADO, Enma  12  Stadium Casablanca    4:37.66   84
15  25.             GARCIA RUIZ, Sara  12      P. San Agustin    5:05.66   63

Modificamos las tablas

In [23]:
t0=tablas[0].df.copy()
t0.loc[10][1]=t0.loc[10][1]+'o'
t0.loc[10][2]='11'
t0=t0[t0[0]!=''][4:]

t1 = tablas[2].df[tablas[2].df[0]!=''][3:].drop(8,axis=1).T.reset_index(drop=True).T
t1 = juntar_columnas(juntar_columnas(separar_columna_derecha(separar_columna(t1,0),6),1,6),3,4)
t1[1]=t1[1].replace({'MENDEZSALVADOR, Carlos':'MENDEZ SALVADOR, Carlos',
                       'PETISMEROYO, Lucas':'PETISME ROYO, Lucas',
                     'PETISMEROYO,Lucas':'PETISME ROYO, Lucas',
                     'RAMOS OLMOS,Diego':'RAMOS OLMOS, Diego',
                      'SANCHEZMERCADO, Adrian':'SANCHEZ MERCADO, Adrian',
                      'MOSTEOHIDALGO, Carlos':'MOSTEO HIDALGO, Carlos',
                      'BERDEJOLOBERA, Guillermo':'BERDEJO LOBERA, Guillermo',
                     'GREGORIO FERNANDEZ,Enrique':'GREGORIO FERNANDEZ, Enrique',
                      'JIMENEZLAFUENTE, Daniel':'JIMENEZ LAFUENTE, Daniel',
                     'SANCHEZSAEZ, Alejandro':'SANCHEZ SAEZ, Alejandro',
                     'SANZ BEJENARIU,Diego':'SANZ BEJENARIU, Diego',
                     'VICENTEBARRA,Guillen':'VICENTE BARRA, Guillen',
                     'RAZABALINGELMO, Angel':'RAZABAL INGELMO, Angel',
                     'NEVADOPEREZ, Lorien':'NEVADO PEREZ, Lorien',
                     'RAMOSOLMOS,Diego':'RAMOS OLMOS, Diego',
                     'MARTINFERNANDEZ, Leo':'MARTIN FERNANDEZ, Leo',
                     'BARRIENDOS ZAMORA,Saul':'BARRIENDOS ZAMORA, Saul',
                     'RAMOSOLMOS,Marcos':'RAMOS OLMOS, Marcos',
                     'RUBIO RAKITIN,Larion Francisco':'RUBIO RAKITIN, Larion Francisco'
                     
                      })
t1[3]=t1[3].replace({'C.N.Helios':'C.N. Helios',
                       'P. SanAgustin':'P. San Agustin',
                     'E.M.El Olivar':'E.M. El Olivar'
                      })


t1b = tablas[3].df[3:]
t1b=t1b[t1b[0]!=''][:-2].drop(4,axis=1).T.reset_index(drop=True).T

t2 = tablas[4].df
t2=t2[t2[0]!=''][2:-1]


# t2b=pd.read_csv('tabla_perdida_27_03_22.csv',dtype=str, header=None).T.reset_index(drop=True).T
# t2b.to_dict()
dic={0: {0: '9', 1: '10', 2: '11', 3: '12', 4: '13', 5: '14', 6: '15'},
 1: {0: 'MARTINEZ MARQUES, Aimar Teresa',
  1: 'GIMENO GOMEZ, Yaretzi Izel',
  2: 'REMACHA ROYO, Itziar',
  3: 'BORREGUERO PEDREIRA, Leire',
  4: 'GALAY TORRIJO, Celia',
  5: 'GARCIA ZABAL, Carmen',
  6: 'IZQUIERDO GRACIA, Maria'},
 2: {0: '13', 1: '13', 2: '13', 3: '13', 4: '13', 5: '13', 6: '13'},
 3: {0: 'Stadium Venecia',
  1: 'P. San Agustin',
  2: 'E.M. El Olivar',
  3: 'E.M. El Olivar',
  4: 'Stadium Venecia',
  5: 'P. San Agustin',
  6: 'Stadium Venecia'},
 4: {0: '1:57.36',
  1: '1:59.80',
  2: '2:07.92',
  3: '2:10.12',
  4: '2:13.72',
  5: '2:15.45',
  6: '2:45.36'},
 5: {0: '102', 1: '96', 2: '79', 3: '75', 4: '69', 5: '66', 6: '36'}}
t2b=pd.DataFrame(dic)

t3 = tablas[6].df
t3=t3[t3[0]!=''][3:]
t3=t3.drop(4,axis=1).T.reset_index(drop=True).T


t3b = tablas[7].df
t3b = t3b[t3b[0]!=''][2:-2].drop(4,axis=1).T.reset_index(drop=True).T


t4=tablas[8].df[3:]

t5=tablas[9].df
t5=t5[t5[0]!=''][4:-3]
t5=separar_columna_derecha(t5,1)


t6=tablas[10].df[3:-1]


t7=tablas[12].df
t7=t7[t7[0]!=''][1:]

t7b=tablas[13].df
t7b=t7b[t7b[0]!=''][2:-6]

In [4]:
t0=separar_columna(tablas[0].df[tablas[0].df[0]!=''][4:],1)
t1 = tablas[1].df[tablas[1].df[0]!=''][3:].drop(8,axis=1).T.reset_index(drop=True).T
t1 = separar_columna(separar_columna(t1,0).fillna(value=''),0,' ').fillna(value='')
t1 = juntar_columnas(juntar_columnas(t1,1,6),3,4)
t1[1]=t1[1].replace({'MENDEZSALVADOR, Carlos':'MENDEZ SALVADOR, Carlos',
                       'PETISMEROYO, Lucas':'PETISME ROYO, Lucas',
                     'RAMOS OLMOS,Diego':'RAMOS OLMOS, Diego',
                      'SANCHEZMERCADO, Adrian':'SANCHEZ MERCADO, Adrian',
                      'MOSTEOHIDALGO, Carlos':'MOSTEO HIDALGO, Carlos',
                      'BERDEJOLOBERA, Guillermo':'BERDEJO LOBERA, Guillermo',
                     'GREGORIO FERNANDEZ,Enrique':'GREGORIO FERNANDEZ, Enrique',
                      'JIMENEZLAFUENTE, Daniel':'JIMENEZ LAFUENTE, Daniel',
                     'SANCHEZSAEZ, Alejandro':'SANCHEZ SAEZ, Alejandro',
                     'SANZ BEJENARIU,Diego':'SANZ BEJENARIU, Diego',
                     'VICENTEBARRA,Guillen':'VICENTE BARRA, Guillen',
                     'RAZABALINGELMO, Angel':'RAZABAL INGELMO, Angel',
                     'NEVADOPEREZ, Lorien':'NEVADO PEREZ, Lorien'                  
                      })
t1[3]=t1[3].replace({'C.N.Helios':'C.N. Helios',
                       'P. SanAgustin':'P. San Agustin',
                      })

# t1b=pd.read_csv('tabla_perdida_20_02_22.csv',dtype=str, header=None).T.reset_index(drop=True).T
# t1b.to_dict()
dic ={0: {0: '21.', 1: '22.', 2: '23.', 3: '24.'},
 1: {0: 'SANTAMARIA FERRERUELA, Carlos',
  1: 'SANCHEZ DUARTE, Rodrigo',
  2: 'CUEZVA JORDAN, Hector',
  3: 'PEREZ DOMINCHE, Oriol'},
 2: {0: '10', 1: '10', 2: '10', 3: '10'},
 3: {0: 'P. San Agustin',
  1: 'Stadium Venecia',
  2: 'Stadium Venecia',
  3: 'C.N. Helios'},
 4: {0: '3:27.36', 1: '3:34.13', 2: '3:34.20', 3: '3:53.64'},
 5: {0: '110', 1: '99', 2: '99', 3: '76'}}
t1b=pd.DataFrame(dic)

t2=tablas[2].df[tablas[2].df[0]!=''][2:]
# separar_columna(t2,2).fillna(value='').loc[17]
t2.loc[17][1]='MARTINEZ MARQUES, Aimar Teresa'
t2.loc[17][2]='13'

# t2b=pd.read_csv('tabla_perdida2_20_02_22.csv',dtype=str, header=None).T.reset_index(drop=True).T
# t2b.to_dict()
dic={0: {0: '10.',
  1: '11.',
  2: '12.',
  3: '13.',
  4: '14.',
  5: '15.',
  6: '16.',
  7: '17.'},
 1: {0: 'GIMENO GOMEZ, Yaretzi Izel',
  1: 'REMACHA ROYO, Itziar',
  2: 'RODRIGO MONFORTE, Lucia',
  3: 'SALUE√ëA LUCHA, Vera',
  4: 'BORREGUERO PEDREIRA, Leire',
  5: 'GALAY TORRIJO, Celia',
  6: 'MARIN PELEGRIN, Sara',
  7: 'MARIN PELEGRIN, Julia'},
 2: {0: '13', 1: '13', 2: '13', 3: '13', 4: '13', 5: '13', 6: '13', 7: '13'},
 3: {0: 'P. San Agustin',
  1: 'E.M. El Olivar',
  2: 'E.M. El Olivar',
  3: 'C.N. Helios',
  4: 'E.M. El Olivar',
  5: 'Stadium Venecia',
  6: 'H2ogo C.N.',
  7: 'H2ogo C.N.'},
 4: {0: '1:49.62',
  1: '1:53.45',
  2: '1:54.02',
  3: '1:57.72',
  4: '2:01.32',
  5: '2:03.50',
  6: '2:09.69',
  7: '2:09.74'},
 5: {0: '96', 1: '86', 2: '85', 3: '77', 4: '71', 5: '67', 6: '58', 7: '58'}}

t2b=pd.DataFrame(dic)

t2c=tablas[3].df[tablas[3].df[0]!=''][2:-2].drop(2,axis=1).T.reset_index(drop=True).T

t3=tablas[4].df[tablas[4].df[0]!=''][3:].drop(8,axis=1).T.reset_index(drop=True).T
t3 = separar_columna(separar_columna(t3,0).fillna(value=''),0,' ').fillna(value='')
t3 = juntar_columnas(juntar_columnas(t3,1,5),3,4)
t3[1]=t3[1].replace({'CASTILLOPRADO, Neus':'CASTILLO PRADO, Neus',
                       'LAMBANGAVE, Ines':'LAMBAN GAVE, Ines',
                     'SIMON HEREDIA,Ariadna':'SIMON HEREDIA, Ariadna',
                      'RAZABALINGELMO, Naiara':'RAZABAL INGELMO, Naiara',
                      'GIMENOMONREAL, Manuela':'GIMENO MONREAL, Manuela',
                      'PERALESCASAS, Laura':'PERALES CASAS, Laura',
                     'BARRACHINA ARTAZCOZ,Nahia':'BARRACHINA ARTAZCOZ, Nahia',
                      'ALONSOMORA,Naiara':'ALONSO MORA, Naiara',
                     'RAZABALINGELMO, Anahi':'RAZABAL INGELMO, Anahi',
                     'ORTEGAFRAGOSO, Emma':'ORTEGA FRAGOSO, Emma',
                     'RASAL ALVAREZ,Maria':'RASAL ALVAREZ, Maria',
                     'CEBRIANPUEYO, Carolina':'CEBRIAN PUEYO, Carolina',
                     'ROMEROLORENTE, Paula':'ROMERO LORENTE, Paula'                  
                      })
t3[3]=t3[3].replace({'C.N.Helios':'C.N. Helios',
                       'P. SanAgustin':'P. San Agustin',
                      })
t3b=tablas[5].df[tablas[5].df[0]!=''][3:].drop(8,axis=1).T.reset_index(drop=True).T
t3b = separar_columna(separar_columna(t3b,0).fillna(value=''),0,' ').fillna(value='')
t3b = juntar_columnas(juntar_columnas(t3b,1,6),3,4)
t3b[1]=t3b[1].replace({'CASTILLOPRADO, Neus':'CASTILLO PRADO, Neus',
                       'LAMBANGAVE, Ines':'LAMBAN GAVE, Ines',
                     'SIMON HEREDIA,Ariadna':'SIMON HEREDIA, Ariadna',
                      'RAZABALINGELMO, Naiara':'RAZABAL INGELMO, Naiara',
                      'GIMENOMONREAL, Manuela':'GIMENO MONREAL, Manuela',
                      'PERALESCASAS, Laura':'PERALES CASAS, Laura',
                     'BARRACHINA ARTAZCOZ,Nahia':'BARRACHINA ARTAZCOZ, Nahia',
                      'ALONSOMORA,Naiara':'ALONSO MORA, Naiara',
                     'RAZABALINGELMO, Anahi':'RAZABAL INGELMO, Anahi',
                     'ORTEGAFRAGOSO, Emma':'ORTEGA FRAGOSO, Emma',
                     'RASAL ALVAREZ,Maria':'RASAL ALVAREZ, Maria',
                     'CEBRIANPUEYO, Carolina':'CEBRIAN PUEYO, Carolina',
                     'ROMEROLORENTE, Paula':'ROMERO LORENTE, Paula'                  
                      })
t3b[3]=t3b[3].replace({'C.N.Helios':'C.N. Helios',
                       'P. SanAgustin':'P. San Agustin',
                      })

t4=separar_columna(tablas[6].df[tablas[6].df[0]!=''][2:],1)
t4.loc[19][1]='MODREGO MARQUETA, Alejandro'
t4.loc[19][2]='11'

# t4b=pd.read_csv('tabla_perdida3_20_02_22.csv',dtype=str, header=None).T.reset_index(drop=True).T
# t4b.to_dict()
dic={0: {0: '10.', 1: '11.'},
 1: {0: 'LOPEZ VELEZ, Marcos', 1: 'BEAMONTE MARTIN, Diego'},
 2: {0: '11', 1: '11'},
 3: {0: 'E.M. El Olivar', 1: 'P. San Agustin'},
 4: {0: '1:48.31', 1: '1:52.44'},
 5: {0: '133', 1: '119'}}
t4b=pd.DataFrame(dic)


t4c=tablas[7].df[tablas[7].df[0]!=''][2:-4]
t4c=separar_columna(t4c,1)

t5=tablas[8].df[tablas[8].df[0]!=''][2:]
t5=juntar_columnas(juntar_columnas(separar_columna(t5,0).fillna(value=''),1,5),3,4).drop(4,axis=1).T.reset_index(drop=True).T
t5[1]=t5[1].replace({'MENDEZSALVADOR, Carlos':'MENDEZ SALVADOR, Carlos',
                       'PETISMEROYO, Lucas':'PETISME ROYO, Lucas',
                     'RAMOS OLMOS,Diego':'RAMOS OLMOS, Diego',
                      'SANCHEZMERCADO, Adrian':'SANCHEZ MERCADO, Adrian',
                      'MOSTEOHIDALGO, Carlos':'MOSTEO HIDALGO, Carlos',
                      'BERDEJOLOBERA, Guillermo':'BERDEJO LOBERA, Guillermo',
                     'GREGORIO FERNANDEZ,Enrique':'GREGORIO FERNANDEZ, Enrique',
                      'JIMENEZLAFUENTE, Daniel':'JIMENEZ LAFUENTE, Daniel',
                     'SANCHEZSAEZ, Alejandro':'SANCHEZ SAEZ, Alejandro',
                     'SANZ BEJENARIU,Diego':'SANZ BEJENARIU, Diego',
                     'VICENTEBARRA,Guillen':'VICENTE BARRA, Guillen',
                     'RAZABALINGELMO, Angel':'RAZABAL INGELMO, Angel',
                     'NEVADOPEREZ, Lorien':'NEVADO PEREZ, Lorien',
                     'RAMOS OLMOS,Marcos':'RAMOS OLMOS, Marcos',
                      })
t5[3]=t5[3].replace({'C.N.Helios':'C.N. Helios',
                       'P. SanAgustin':'P. San Agustin',
                      })

t5b=tablas[9].df[tablas[9].df[0]!=''][2:]
t5b=juntar_columnas(juntar_columnas(separar_columna(separar_columna(t5b,0),0,' ').fillna(value=''),1,6),3,4).drop(4,axis=1).T.reset_index(drop=True).T
t5b[1]=t5b[1].replace({'MENDEZSALVADOR, Carlos':'MENDEZ SALVADOR, Carlos',
                       'PETISMEROYO, Lucas':'PETISME ROYO, Lucas',
                     'RAMOS OLMOS,Diego':'RAMOS OLMOS, Diego',
                      'SANCHEZMERCADO, Adrian':'SANCHEZ MERCADO, Adrian',
                      'MOSTEOHIDALGO, Carlos':'MOSTEO HIDALGO, Carlos',
                      'BERDEJOLOBERA, Guillermo':'BERDEJO LOBERA, Guillermo',
                     'GREGORIO FERNANDEZ,Enrique':'GREGORIO FERNANDEZ, Enrique',
                      'JIMENEZLAFUENTE, Daniel':'JIMENEZ LAFUENTE, Daniel',
                     'SANCHEZSAEZ, Alejandro':'SANCHEZ SAEZ, Alejandro',
                     'SANZ BEJENARIU,Diego':'SANZ BEJENARIU, Diego',
                     'VICENTEBARRA,Guillen':'VICENTE BARRA, Guillen',
                     'RAZABALINGELMO, Angel':'RAZABAL INGELMO, Angel',
                     'NEVADOPEREZ, Lorien':'NEVADO PEREZ, Lorien',
                     'RAMOS OLMOS,Marcos':'RAMOS OLMOS, Marcos',
                       'SANCHEZ SAEZ,Alejandro':'SANCHEZ SAEZ, Alejandro',
                       'DANIELROYO, Carlos':'DANIEL ROYO, Carlos',
                       'MARTINFERNANDEZ, Leo':'MARTIN FERNANDEZ, Leo',
                       'CUEZVAJORDAN, Hector':'CUEZVA JORDAN, Hector',
                       'ESTAUNLOPEZ,Marcos':'ESTAUN LOPEZ, Marcos',
                       'NEVADOPEREZ,Lorien':'NEVADO PEREZ, Lorien',
                       
                       
                      })
t5b[3]=t5b[3].replace({'C.N.Helios':'C.N. Helios',
                       'P. SanAgustin':'P. San Agustin',
                      })
# t6=pd.read_csv('tabla_perdida4_20_02_22.csv',dtype=str, header=None).T.reset_index(drop=True).T
# dic=t6.to_dict()

dic={0: {0: '1.', 1: '2.', 2: '3.', 3: '4.', 4: '5.'},
 1: {0: 'ESCORIHUELA AZNAR, Claudia',
  1: 'RODRIGUEZ SOLANAS, Ines',
  2: 'MALON CANTIN, Sofia',
  3: 'MALO SANCHEZ, Paula',
  4: 'REMACHA ROYO, Itziar'},
 2: {0: '13', 1: '13', 2: '13', 3: '13', 4: '13'},
 3: {0: 'E.M. El Olivar',
  1: 'E.M. El Olivar',
  2: 'C.N. Helios',
  3: 'C.N. Helios',
  4: 'E.M. El Olivar'},
 4: {0: '1:59.04', 1: '2:02.81', 2: '2:07.84', 3: '2:09.72', 4: '2:09.95'},
 5: {0: '143', 1: '130', 2: '116', 3: '111', 4: '110'}}
t6=pd.DataFrame(dic)


t6b=tablas[10].df[tablas[10].df[0]!=''][2:-4]

t6b.loc[13][1]='MARTINEZ MARQUES, Aimar Teresa'
t6b.loc[13][2]='13'

# t7=pd.read_csv('tabla_perdida5_20_02_22.csv',dtype=str, header=None).T.reset_index(drop=True).T
# dic=t7.to_dict()

dic={0: {0: '1.', 1: '2.', 2: '3.', 3: '4.', 4: '5.'},
 1: {0: 'CASTILLO PRADO, Neus',
  1: 'IOVU, Mireya',
  2: 'GIL FUENTES, Izarbe',
  3: 'BERGES ALAEZ, Africa',
  4: 'GIMENO MONREAL, Manuela'},
 2: {0: '12', 1: '12', 2: '12', 3: '12', 4: '12'},
 3: {0: 'E.M. El Olivar',
  1: 'P. San Agustin',
  2: 'Stadium Venecia',
  3: 'E.M. El Olivar',
  4: 'E.M. El Olivar'},
 4: {0: '3:36.21', 1: '3:53.82', 2: '3:56.09', 3: '3:57.59', 4: '3:58.62'},
 5: {0: '241', 1: '190', 2: '185', 3: '181', 4: '179'}}

t7=pd.DataFrame(dic)

t7b = tablas[11].df[tablas[11].df[0]!=''][2:-1].drop(8,axis=1).T.reset_index(drop=True).T
t7b = separar_columna(separar_columna(t7b,0).fillna(value=''),0,' ').fillna(value='')
t7b = juntar_columnas(juntar_columnas(t7b,1,6),3,4)
t7b[1]=t7b[1].replace({'CASTILLOPRADO, Neus':'CASTILLO PRADO, Neus',
                       'LAMBANGAVE, Ines':'LAMBAN GAVE, Ines',
                     'SIMON HEREDIA,Ariadna':'SIMON HEREDIA, Ariadna',
                      'RAZABALINGELMO, Naiara':'RAZABAL INGELMO, Naiara',
                      'GIMENOMONREAL, Manuela':'GIMENO MONREAL, Manuela',
                      'PERALESCASAS, Laura':'PERALES CASAS, Laura',
                     'BARRACHINA ARTAZCOZ,Nahia':'BARRACHINA ARTAZCOZ, Nahia',
                      'ALONSOMORA,Naiara':'ALONSO MORA, Naiara',
                     'RAZABALINGELMO, Anahi':'RAZABAL INGELMO, Anahi',
                     'ORTEGAFRAGOSO, Emma':'ORTEGA FRAGOSO, Emma',
                     'RASAL ALVAREZ,Maria':'RASAL ALVAREZ, Maria',
                     'CEBRIANPUEYO, Carolina':'CEBRIAN PUEYO, Carolina',
                     'ROMEROLORENTE, Paula':'ROMERO LORENTE, Paula',
                     'SIMONHEREDIA, Ariadna':'SIMON HEREDIA, Ariadna',
                     
                      })
t7b[3]=t7b[3].replace({'C.N.Helios':'C.N. Helios',
                       'P. SanAgustin':'P. San Agustin',
                      })

In [72]:
# Liga Benjamin

competicion = 'Benjam√≠n, jornada 6'
lugar = 'E.M. El Olivar'
fecha = datetime.datetime(2022,4,24)


lista_df=[
tabla_a_datos(t0, fila_datos = 0, fecha=fecha, prueba='200m Libre', m_f='M', tipo=1, competicion=competicion, lugar= lugar),
tabla_a_datos(t1, fila_datos = 0, fecha=fecha, prueba='400m Libre', m_f='M', tipo=1, competicion=competicion, lugar= lugar),
tabla_a_datos(t1b, fila_datos = 0, fecha=fecha, prueba='400m Libre', m_f='M', tipo=1, competicion=competicion, lugar= lugar),

# tabla_a_datos(t1b, fila_datos = 0, fecha=fecha, prueba='200m Espalda', m_f='M', tipo=1, competicion=competicion, lugar= lugar),
tabla_a_datos(t2, fila_datos = 0, fecha=fecha, prueba='200m Libre', m_f='F', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t2b, fila_datos = 0, fecha=fecha, prueba='100m Espalda', m_f='F', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t3, fila_datos = 0, fecha=fecha, prueba='200m Espalda', m_f='F', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t3b, fila_datos = 0, fecha=fecha, prueba='200m Espalda', m_f='F', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t4, fila_datos = 0, fecha=fecha, prueba='50m Mariposa', m_f='M', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t5, fila_datos = 0, fecha=fecha, prueba='100m Mariposa', m_f='M', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t6, fila_datos = 0, fecha=fecha, prueba='50m Mariposa', m_f='F', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t7, fila_datos = 0, fecha=fecha, prueba='100m Mariposa', m_f='F', tipo=1, competicion=competicion, lugar= lugar),
# tabla_a_datos(t7b, fila_datos = 0, fecha=fecha, prueba='100m Mariposa', m_f='F', tipo=1, competicion=competicion, lugar= lugar),

 ]

for d in lista_df :
    display(d)
    
    
campos_calculados(pd.concat(lista_df)).to_csv('competicion_'+competicion+'.csv', index=False)

,Puesto,Nombre,Anyo_nac,Club,Tiempo,Pts,Fecha,Prueba,Piscina,M_F,Competicion,Lugar
0,1.,"MARCO LOPEZ, Leo",11,C.N. Helios,2:48.02,206,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
1,2.,"LOPEZ VELEZ, Marcos",11,E.M. El Olivar,2:50.56,197,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
2,3.,"MODREGO MARQUETA, Alejandro",11,Stadium Venecia,2:50.89,196,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
3,4.,"RODRIGUEZ ARTIEDA, Marcelo",11,C.N. Helios,2:52.84,190,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
4,5.,"CAVERO GARCIA, Daniel",11,Stadium Casablanca,2:55.97,180,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
5,6.,"BELTRAN VIEJO, Arturo",11,E.M. El Olivar,2:56.81,177,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
6,7.,"SERRABLO HUESO, Diego",11,Stadium Venecia,2:57.94,174,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
7,8.,"MARTINEZ ANTUNEZ, Roman",11,Stadium Venecia,2:59.97,168,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
8,9.,"BESCOS RODRIGUEZ, Jesus",11,E.M. El Olivar,3:03.42,159,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
9,10.,"POLO MARTINEZ, Nicolas",11,C.N. Helios,3:06.09,152,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
10,11.,"FABRE GARCIA, Guillermo",11,E.M. El Olivar,3:07.04,149,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
11,12.,"SANCHO GRAUS, Bruno",11,E.M. El Olivar,3:07.80,148,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
12,13.,"FANDOS MARCO, Carlos",11,E.M. El Olivar,3:08.09,147,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
13,14.,"ANGUAS FELIZ, Aquiles",11,E.M. El Olivar,3:09.44,144,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
14,15.,"ANTONENKO ANTONENKO, Yehor",11,H2ogo C.N.,3:10.84,141,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
15,16.,"LAFUENTE GARCIA, Victor",11,C.N. Helios,3:14.48,133,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
16,17.,"ROMERO SANTOS, Kilian",11,C.N. Helios,3:22.47,118,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
17,18.,"GARCIA DE LA SERNA, Alejandro",11,C.N. Helios,3:24.98,113,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
18,19.,"PELEGRIN RUIZ, Raul",11,C.N. Helios,3:25.29,113,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
19,20.,"BARCELONA PERALES, Beltran",11,E.M. El Olivar,3:43.44,87,2022-04-24,200m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar

,Puesto,Nombre,Anyo_nac,Club,Tiempo,Pts,Fecha,Prueba,Piscina,M_F,Competicion,Lugar
0,1.,"MENDEZ SALVADOR, Carlos",10,C.N. Teruel,5:24.42,280,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
1,2.,"MARTIN FERNANDEZ, Leo",10,E.M. El Olivar,5:28.18,270,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
2,3.,"BARRIENDOS ZAMORA, Saul",10,C.N. Helios,5:48.15,226,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
3,4.,"RAMOS OLMOS, Diego",10,P. San Agustin,5:53.38,216,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
4,5.,"RAMOS OLMOS, Marcos",10,P. San Agustin,5:57.25,209,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
5,6.,"SANCHEZ MERCADO, Adrian",10,Stadium Casablanca,6:04.97,196,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
6,7.,"MOSTEO HIDALGO, Carlos",10,E.M. El Olivar,6:18.73,176,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
7,8.,"BERDEJO LOBERA, Guillermo",10,E.M. El Olivar,6:18.82,175,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
8,9.,"JIMENEZ LAFUENTE, Daniel",10,C.N. Helios,6:25.09,167,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
9,10.,"SANCHEZ SAEZ, Alejandro",10,P. San Agustin,6:26.08,166,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
10,11.,"SHAPOVAL, Maksym",10,Stadium Venecia,6:32.31,158,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
11,12.,"RUBIO RAKITIN, Larion Francisco",10,C.N. Helios,6:33.18,157,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
12,13.,"ESTAUN LOPEZ, Marcos",10,C.N. Helios,6:33.84,156,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
13,14.,"GREGORIO FERNANDEZ, Enrique",10,P. San Agustin,6:36.91,152,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
14,15.,"REVUELTO TELLO, Alejandro",10,E.M. El Olivar,6:44.23,144,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
15,16.,"SANZ BEJENARIU, Diego",10,C.N. Iz Cuarte,6:44.59,144,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
16,17.,"RAZABAL INGELMO, Angel",10,E.M. El Olivar,6:52.60,136,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar

,Puesto,Nombre,Anyo_nac,Club,Tiempo,Pts,Fecha,Prueba,Piscina,M_F,Competicion,Lugar
0,18.,"CUEZVA JORDAN, Hector",10,Stadium Venecia,7:15.39,115,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar
1,19.,"SANCHEZ DUARTE, Rodrigo",10,Stadium Venecia,7:30.22,104,2022-04-24,400m Libre,25m,M,"Benjam√≠n, jornada 6",E.M. El Olivar

,Puesto,Nombre,Anyo_nac,Club,Tiempo,Pts,Fecha,Prueba,Piscina,M_F,Competicion,Lugar
0,1.,"RODRIGUEZ SOLANAS, Ines",13,E.M. El Olivar,3:39.29,171,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
1,2.,"MARTIN SORIA, Claudia",13,Stadium Venecia,3:41.78,165,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
2,3.,"MALON CANTIN, Sofia",13,C.N. Helios,3:42.75,163,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
3,4.,"MALO SANCHEZ, Paula",13,C.N. Helios,3:45.48,157,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
4,5.,"ESCORIHUELA AZNAR, Claudia",13,E.M. El Olivar,3:50.59,147,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
5,6.,"GAINSINSKY CASTILLO, Michelle",13,C.N. Helios,3:53.56,142,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
6,7.,"DEL BARRIO MIGUEL, Vera",13,Stadium Venecia,3:59.60,131,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
7,8.,"RODRIGO MONFORTE, Lucia",13,E.M. El Olivar,4:04.36,124,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
8,9.,"LEAL PELEGRIN, Julieta",13,E.M. El Olivar,4:05.81,121,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
9,10.,"GIMENO GOMEZ, Yaretzi Izel",13,P. San Agustin,4:11.51,113,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
10,11.,"RODRIGO LORENTE, Claudia",13,Stadium Venecia,4:14.41,109,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
11,12.,"ZAPATA FERNANDEZ, Jara",13,Stadium Venecia,4:17.18,106,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
12,13.,"REMACHA ROYO, Itziar",13,E.M. El Olivar,4:17.73,105,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
13,14.,"MARTINEZ MARQUES, Aimar Teresa",13,Stadium Venecia,4:27.62,94,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
14,15.,"BORREGUERO PEDREIRA, Leire",13,E.M. El Olivar,4:42.56,80,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
15,16.,"GARCIA RODRIGUEZ, Aroa",13,C.N. Helios,4:57.91,68,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
16,17.,"ROLDAN POZO, Adriana",13,P. San Agustin,5:11.00,60,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
17,18.,"GARCIA ZABAL, Carmen",13,P. San Agustin,5:21.41,54,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar
18,19.,"MATA AGUELA, Candela",13,E.M. El Olivar,5:21.54,54,2022-04-24,200m Libre,25m,F,"Benjam√≠n, jornada 6",E.M. El Olivar

Hacemos un resumen de los datos contando el n√∫mero de nadadores por club:

In [73]:
# Resumen de datos

df=pd.read_csv('competicion_'+competicion+'.csv')

#df.pivot_table(df, values = 'Nombre',index='M_F', columns=['Club','Anyo_nac'], aggfunc=lambda x: len(x.unique()))
df.pivot_table(values = 'Nombre', columns='M_F', index=['Club','Anyo_nac'], aggfunc=lambda x: len(x.unique())).unstack().fillna(0).astype(int)

M_F                 F        M
Anyo_nac           10 11 13 10 11 13
Club
C.N. Helios         0  0  4  4  7  0
C.N. Iz Cuarte      0  0  0  1  0  0
C.N. Teruel         0  0  0  1  0  0
E.M. El Olivar      0  0  7  5  8  0
H2ogo C.N.          0  0  0  0  1  0
P. San Agustin      0  0  3  4  0  0
Stadium Casablanca  0  0  0  1  1  0
Stadium Venecia     0  0  5  3  3  0

Por √∫ltimo, a√±adimos todas las competiciones al archivo *base_datos.csv*:

In [74]:
# Actualizamos la base de datos

import glob

# Buscamos todos los ficheros csv correspondientes a competiciones los concatenamos y los grabamos en base de datos

lista_competiciones = glob.glob('competicion*.csv')
# lista_competiciones.reverse()
lista_competiciones.sort()
df=pd.concat([pd.read_csv(comp) for comp in lista_competiciones])
# df.sort_values(by='Fecha').to_csv('base_datos.csv', index=False)
df.to_csv('base_datos.csv', index=False)

# lista_competiciones.reverse()
lista_competiciones

['competicion_Benjam√≠n, jornada 1.csv',
 'competicion_Benjam√≠n, jornada 2.csv',
 'competicion_Benjam√≠n, jornada 3.csv',
 'competicion_Benjam√≠n, jornada 4.csv',
 'competicion_Benjam√≠n, jornada 5.csv',
 'competicion_Benjam√≠n, jornada 6.csv']